#!/bin/bash

npm run playground &
while ! nc -z localhost 8000; do
  sleep 0.5
done

wget -P docs/demo -nH -r http://127.0.0.1:8000/{,tree-sitter.wasm,tree-sitter-parser.wasm}
sed -i 's,LANGUAGE_BASE_URL = "";,LANGUAGE_BASE_URL = new URL(window.location.href).pathname;,' docs/demo/index.html

