#!/bin/bash

set -eEu

npx tree-sitter build-wasm
timeout 3s npx tree-sitter playground &
job=$!

while ! nc -z localhost 8000; do
  sleep 0.5
done

wget -P playground -nH -r http://127.0.0.1:8000/{,tree-sitter.wasm,tree-sitter-parser.wasm}
sed -i 's,LANGUAGE_BASE_URL = "";,LANGUAGE_BASE_URL = new URL(window.location.href).pathname;,' playground/index.html

wait $job || exit 0
